### PR TITLE
Add iOS and Android app bundle builds

### PR DESCRIPTION
**Pull request by AlessioLuciani**
Solving issue https://github.com/subosito/flutter-action/issues/7 and https://github.com/subosito/flutter-action/issues/42.

### CODE REVIEW

**Comment by jordandearsley** [comment]
Would really love this feature!

**Comment by RicardoRB** [comment]
Someone can merge it? It is just a Readme modification

**Comment by djpnewton** [comment]
example that only builds for iOS installs java which is unnecessary

**Comment by AlessioLuciani** [comment]
> example that only builds for iOS installs java which is unnecessary

Yes, in case you just want to build for iOS I think Java is not necessary. By the way, in the example I added it builds for both platforms, so Java is required.

**Comment by ajbarry** [comment]
@AlessioLuciani perhaps you might also suggest how to build the web app:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
```

I would submit my own PR but it would cause a conflict 😝

**Comment by AlessioLuciani** [comment]
> @AlessioLuciani perhaps you might also suggest how to build the web app:
> 
> ```yaml
> jobs:
>   build:
>     runs-on: ubuntu-latest
>     steps:
>     - uses: actions/checkout@v1
>     - uses: subosito/flutter-action@v1
>       with:
>         channel: beta
>     - run: flutter config --enable-web
>     - run: flutter pub get
>     - run: flutter test
>     - run: flutter build web
> ```
> 
> I would submit my own PR but it would cause a conflict 😝

Thank you for your suggestion! Just committed that.

**Comment by ajbarry** [comment]
@AlessioLuciani Nice! #teamwork!

**Comment by AlessioLuciani** [comment]
> Someone can merge it? It is just a Readme modification

A few days ago I sent an email to the maintainer about this, but I haven't received a reply so far 😣

**Comment by ajbarry** [comment]
BTW this PR would supersede #44 but the example in this PR seems to me like a better approach to recommend.

**Comment by tillchen** [comment]
💯

**Comment by subosito** [comment]
Excellent, thanks all. Sorry for the delay, has been busy lately.

**Pull request merged**
