### PR TITLE
Add dry-run

### PR DESCRIPTION
**Pull request by kzrnm**
I want `dry-run` parameter for printing.

### CODE REVIEW

**Comment by subosito** [comment]
@kzrnm Any use case for this?

**Comment by kzrnm** [comment]
For running version checks during scheduled events. Installation of Flutter is not necessary.

```yml
on:
  schedule:
    - cron: '30 5 * * 2,4'
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          dry-run: true
      - run: |
          VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo $VERSION
          # Compare $VERSION and ${{ inputs.current-version }}
          # Notify version...
```

**Comment by bartekpacia** [comment]
Interesting. So you would want to have notifications about new Flutter versions, right?

Or to auto-rebuild your app when a new Flutter version comes out?

**Comment by kzrnm** [comment]
> So you would want to have notifications about new Flutter versions, right?

I don't need it if I'm developing alone, but it may be necessary if I'm developing in a team.

**Comment by bartekpacia** [comment]
Hi! Thank you for the contribution. Could you add tests and update README to reflect your changes?

**Comment by kzrnm** [comment]
Is this test correct?

https://github.com/subosito/flutter-action/pull/270/commits/03fa8911d9390ae6e83b7fbb02ae94543b1ea872

**Comment by bartekpacia** [comment]
Yes this is good! I'd also like to see another test that asserts that `dart` and `flutter` fail (=are not found) when `dry-run: true` is passed. Just to make sure that it indeed works.

Please also resolve conflitcts - sorry about that!

**Pull request merged**
