### PR TITLE
Add support for reading Flutter version from config files

### LINKED ISSUE #47: Link to pubspec.yaml instead of specifying version
Currently, when a new flutter version is released and one wants to update their project, one must always change the version in `pubspec.yaml` and the version in the github action. 

This is not terribly, but a little annoyance because one has to keep it in mind when changing the version.

I came up with three ideas to solve this:
1. In the yaml github action file link to the version in pubspec.yaml
2. Add a script to the github action file that substitutes the version  when the github action is executed
3. Ask if the feature can be added.

The first version is not possible, as far as I understand it, because in yaml [one can' t reference to a line in another file](https://stackoverflow.com/questions/22639727/yaml-reference-another-variable-in-another-file).

The second solution is probably not possible either, because one would have to replace the github action file while it is running. Did not test this.

I can't think of any other solution at the moment, so I'm asking if you consider this a problem and want to implement it.

### LINKED ISSUE #101: Support reading Flutter version from config file (FVM)
I want to bring this up for consideration. FVM (https://github.com/leoafarias/fvm) is a pretty popular version manager for Flutter. It would be great if the action would support reading the Flutter version/channel from its config file in `.fvm/fvm_config.json` similar to the ruby action and others.

Currently I am reading the version manually from the JSON file in every pipeline:
```yaml
      - name: Determine Flutter version
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: '.fvm/fvm_config.json'
          prefix: fvm
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.fvm_flutterSdkVersion }}
```

This could just be something like this:
```yaml
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '.fvm/fvm_config.json'
```

I would love to create a PR if there is interest for this.

### PR DESCRIPTION
**Pull request by kuhnroyal**
* add basic parsers for pubspec.yaml and FVM config
* add tests
* update README
* resolves #47
* resolves #101

### CODE REVIEW

**Comment by subosito** [comment]
Thanks for the PR @kuhnroyal, I appreciate it.

I was thinking similar solution in https://github.com/subosito/flutter-action/issues/47#issuecomment-830146625. But that's become an issue when we need to support various configs other than `pubspec.yaml`  and when needed additional parameters.

For this case, I prefer having separate action to do the parsing and pass it to flutter-action. So we can focus on the strength of each action.

I propose something like:

```
- uses: subosito/flutter-version@v1
  id: flutter-version
  with:
    adapter: 'pubspec'
    path: 'path/to/custom/pubspec.yaml' # optional, default to pubspec.yaml
- uses: subosito/flutter-action@v1
  with:
    flutter-version: "{{ steps.flutter-version.outputs.VERSION }}"
```

What do you think?

**Comment by kuhnroyal** [comment]
I don't know, You can pretty much do it the same way with any of the JSON/Yaml-path actions. It is not much of an improvement then tbh.

**Comment by kuhnroyal** [comment]
But yea the path needs to be configurable. Didn't think about that.

**Comment by kuhnroyal** [comment]
Maybe set the version into the environment and the read it from there.

```yaml
- uses: subosito/flutter-version@v1
  with:
    adapter: 'pubspec'
    path: 'path/to/custom/pubspec.yaml' # optional, default to pubspec.yaml
- uses: subosito/flutter-action@v1
```

This would also allow simply usage like:

```yaml
env:
  FLUTTER_VERSION: 2.0.6

...
- uses: subosito/flutter-action@v1
```

**Comment by benPesso** [comment]
> Maybe set the version into the environment and the read it from there.
> 
> ```yaml
> - uses: subosito/flutter-version@v1
>   with:
>     adapter: 'pubspec'
>     path: 'path/to/custom/pubspec.yaml' # optional, default to pubspec.yaml
> - uses: subosito/flutter-action@v1
> ```
> 
> This would also allow simply usage like:
> 
> ```yaml
> env:
>   FLUTTER_VERSION: 2.0.6
> 
> ...
> - uses: subosito/flutter-action@v1
> ```

This will just move the original issue from the action to the shared secrets - the fact that the version number still needs to be maintained in more than one place.

**Comment by kuhnroyal** [comment]
> > Maybe set the version into the environment and the read it from there.
> > ```yaml
> > - uses: subosito/flutter-version@v1
> >   with:
> >     adapter: 'pubspec'
> >     path: 'path/to/custom/pubspec.yaml' # optional, default to pubspec.yaml
> > - uses: subosito/flutter-action@v1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This would also allow simply usage like:
> > ```yaml
> > env:
> >   FLUTTER_VERSION: 2.0.6
> > 
> > ...
> > - uses: subosito/flutter-action@v1
> > ```
> 
> This will just move the original issue from the action to the shared secrets - the fact that the version number still needs to be maintained in more than one place.

Not in the first case. The 2nd case is just something that would also work if needed when setting/reading it from the environment.

**Comment by kuhnroyal** [comment]
@subosito How do you want to proceed with this?

**Comment by kuhnroyal** [comment]
Added a custom action for FVM - see #101 
Other setup actions can follow the same path I suppose.

**Pull request closed without merging**
